lang: en
title: SS://portfolio
copyright: © 2024. All rights reserved.

url: "https://shivrajshere.github.io"
baseurl: ""

author:
  name: Shivraj
  social:
    - [github, shivrajshere]
    - [email, shivrajshere4@gmail.com]

plugins:
  - jekyll-feed
  - jekyll-seo-tag

